### ISSUE TITLE
bad argument #18 to 'send' (number or boolean expected, got nil)

### ISSUE THREAD

**Issue by FreeBlues** [egordorichev/neko8#1]
Error info:

```
Air:neko8 admin$ love .
[INFO  01:17:21] main.lua:30: neko 8 v0.0.3 kitten
Error: main.lua:2241: bad argument #18 to 'send' (number or boolean expected, got nil)
stack traceback:
	[C]: in function 'send'
	main.lua:2241: in function 'initPalette'
	main.lua:415: in function 'init'
	main.lua:35: in function 'load'
	main.lua:255: in function <main.lua:245>
	[C]: in function 'xpcall'
Air:neko8 admin$
```

Love2d version: 0.10.1
Platform: MacOS Sierra 10.12.6

I think maybe your love2d version is different from mine, but you have not say which version in use.

**Comment by egordorichev** [comment]
Thank you for the feedback! Try to upgrade your love to **0.10.2**. If that doesn't help, let me know, and I will look for a fix in the code.

**Comment by FreeBlues** [comment]
It is OK!  when I upgrade love to 0.10.2, Thanks!

And I tried run it on iOS, it works very well! !

**Comment by egordorichev** [comment]
Great to hear! Adding that to REAME.

**Comment by egordorichev** [comment]
@FreeBlues, one thing you could do, is joining fantasy consoles server: https://discord.gg/DPBN8Xn I post updates in #other-consoles channel, and you can easily contact me there.

**Comment by FreeBlues** [comment]
Thank you for the invite, I will try to learn how to use discord.
