### ISSUE TITLE
On iOS the terminal`s prompt(>) and red rect cursor  disappeared, can not input anything

### ISSUE THREAD

**Issue by FreeBlues** [egordorichev/neko8#14]
On iOS the terminal`s prompt(>) and red rect cursor  disappeared, can not input anything

the keyboard can display, but can not input anything.

**Comment by egordorichev** [comment]
What build are you using?

**Comment by FreeBlues** [comment]
The newest one, the release directory one is old, I build it myself

**Comment by egordorichev** [comment]
Does it happen every time, you run neko8?

**Comment by FreeBlues** [comment]
Yes ,every time, when I launch it from love2d, at the beginning, display the help info, then stop, without the prompt

**Comment by egordorichev** [comment]
Hm, could you record a gif somehow? Or make a screenshot. Please.

**Comment by FreeBlues** [comment]
It the screen record is a big one about 9M, need time to upload...

[Uploading iOS_Movie_2017-09-13_12-42-27.mov.zip…]()

Too slow, I stopped and upload the record video to here:

http://v.youku.com/v_show/id_XMzAyMDY3ODY1Mg==.html?spm=a2h3j.8428770.3416059.1

**Comment by egordorichev** [comment]
Oh, that's strange.. Does this happen on all devices?

**Comment by FreeBlues** [comment]
screenshots

![img_1133](https://user-images.githubusercontent.com/3386551/30339317-38d36adc-9821-11e7-8872-b7423240bb32.png)
![img_1132](https://user-images.githubusercontent.com/3386551/30339318-395e7c58-9821-11e7-8c5e-bb38bc37c335.png)

On android, I am working on...

**Comment by egordorichev** [comment]
Really strange... Something with neko.n8, I guess.

**Comment by FreeBlues** [comment]
After tried I think I have found the reason, because of the neko.n8 the previous version saved, when you  update a new neko8.love, but the neko.n8 on the iPad(the previous neko8.love saved) will not be deleted or updated, it still there, and the neko8.love will load it prefer....

**Comment by egordorichev** [comment]
Yup, those little bugs with two save directories 😆 Does it fix, if you delete the old one?

**Comment by FreeBlues** [comment]
I can not delete the old one, because on iOS, I can not enter the correct neko.n8, so cant delete it. 

I have 2 love2d.app installed on my iPad, one has a bad old neko.n8, the other has a new and good one.
The bug is still there because of the neko8`s loading mechanism, it means that when you launch neko8, and modify neko.n8, every time your change should be correct, otherwise the wrong change will saved in the neko.n8, if the mistake would make the input stop or make the neko8 can not boot,  you can not change it back.

**Comment by PibePlayer** [comment]
You cannot delete neko.n8 from the app itself?
rm neko.n8

**Comment by FreeBlues** [comment]
@PibePlayer thanks for the response. Although I can not enter in the terminal to execute the rm cmd, but your advice  give me an idea of how to deal with the problem. :)

Add these lines into ./src/neko8.lua

```
      -- Be careful!!! Pls keep in comment
      -- Only use to remove old wrong neko.n8 in the system saved folder
      cmd = require "commands"
      cmd.rm({"neko.n8"})
  
      editors = require "editors"
      editors.init()
``` 

Because of these commands executed before the old neko.n8 was loaded, so the old one will be deleted and the neko8.love will have to load the new one. So the old wrong neko.n8 is avoid!
