### ISSUE TITLE
Multiple crlf

### ISSUE THREAD

**Issue by incinirate** [egordorichev/neko8#18]
While looking at 1aa3387, I noticed that neko8 is replacing `\r\n` with `\n`, I'm not sure if it's worth implementing, but it should be noted that it is valid in windows to have multiple `\r`s before the `\n` indicating multiple line breaks.

**Comment by PibePlayer** [comment]
Yeah, because in Windows, neko.n8 has CRLF line endings, that breaks the cart.lua line break and sections finding method, so this is the easiest way to make it to work, also, *.n8 files are edited inside neko8, so they will have only \n line endings

**Comment by PibePlayer** [comment]
Fixed in commit 742ac60
