### ISSUE TITLE
Some potentially erroneous things in helpers.hpp

### ISSUE THREAD

**Issue by incinirate** [egordorichev/neko8#28]
In [`helpers.hpp`](https://github.com/egordorichev/neko8/blob/c/src/helpers.hpp), you return a pointer allocated on the stack, which is unsafe.

> C++ allows you to return a pointer to an array from a local scope, but it is undefined behavior to use the memory pointed to by this pointer outside of its local scope.

Also the `result` is not allocated, rather it overwrites `w1`, also of which the amount of allocated memory is unknown. It could have enough space to concatenate `w2` to it, but it probably doesn't, which is a memory violation.

Suggested revision:
```c++
char* concat(const char* w1, const char* w2){
	char* result = new char[strlen(w1) + strlen(w2)];
	strcpy(result, w1);
	strcat(result, w2);
	return result;
}
```

And then make sure to `delete[]` afterwards, so usage would be like:
```c++
char* result = concat(strOne, strTwo);
// Do something with result
delete[] result;
```

**Comment by incinirate** [comment]
Nevermind, as long as `w1` contains enough room to contain both `w1` and `w2`, the first point is mute, but still, in general case it's not safe.

**Comment by PibePlayer** [comment]
ooh, thanks, @incinirate, I didn't think on that

**Comment by egordorichev** [comment]
One question:

```c++
neko_graphics *init(neko *machine) {
		neko_graphics *graphics = new neko_graphics;

		// Attempt to open a centred window
		graphics->window = SDL_CreateWindow(
			"neko8", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,
			machine->config->windowWidth, machine->config->windowHeight,
			SDL_WINDOW_SHOWN | SDL_WINDOW_RESIZABLE
		);

		if (NOT(graphics->window)) {
			// We failed, so there is nothing to do for us, abort
			std::cerr << "Failed to open window, aborting\n";
			SDL_Quit();
			exit(1);
		}

		// Attempt to create renderer
		graphics->renderer = SDL_CreateRenderer(graphics->window, -1, SDL_RENDERER_ACCELERATED);

		if (NOT(graphics->renderer)) {
			// We failed, so there is nothing to do for us, abort
			std::cerr << "Failed to create a renderer, aborting\n";
			SDL_Quit();
			exit(2);
		}

		return graphics;
	}
```

Is using `new` here also a bad idea?

**Comment by incinirate** [comment]
@egordorichev Actually that's the correct usage, just make sure that on cleanup (wherever you `SDL_Quit()`) you `delete` it.

**Comment by egordorichev** [comment]
Yup, I'm doing that. Thanks.
